### Module strUtils
SUBMODULE_INSTANCES_MANAGER_COMMANDER=$(MODULE_INSTANCES_STATEMACHINE)/Commander_inst
MODOBJ_INSTANCES_MANAGER_COMMANDER=$(TST_DIR)/commander_inst.o

$(MODOBJ_INSTANCES_MANAGER_COMMANDER): $(shell find $(SUBMODULE_INSTANCES_MANAGER_COMMANDER) $(FNDARGS) )
	$(SAFE) $(MKC) $(SUBMODULE_INSTANCES_MANAGER_COMMANDER) full_mod

