### Module Commander
MODULE_COMMANDER=$(SRC_DIR)/Commander
MODOBJ_COMMANDER_OBJ=$(TST_DIR)/commander.o
MODOBJ_COMMANDER_LIST=$(TST_DIR)/commanderList.o

MODOBJ_COMMANDER=$(MODOBJ_COMMANDER_OBJ) $(MODOBJ_COMMANDER_LIST)

$(MODOBJ_COMMANDER): $(shell find $(MODULE_COMMANDER) $(FNDARGS) )
	$(SAFE) $(MKC) $(MODULE_COMMANDER) full_mod

