# Makefile Commander

## Import config
ROOTDIR=$(realpath ../../)
ifndef CONFIG_SOURCED

CFG_MAKE=$(ROOTDIR)/Config.Makefile
include $(CFG_MAKE)


endif

## Module files
SRC_BASE=cfgUtils
MODULE_DIRECTORY=$(MODULE_CFGUTILS)

## Side module info
HAS_SIDEMOD=false

# System
include $(RULES_MAKE)
