# Makefile Commander

## Import config
ROOTDIR=$(realpath ../../)
ifndef CONFIG_SOURCED

CFG_MAKE=$(ROOTDIR)/Config.Makefile
include $(CFG_MAKE)

endif

## Module files
SRC_BASE=strUtils
MODULE_DIRECTORY=$(MODULE_STRUTILS)

## Side module info
HAS_SIDEMOD=false

# System
include $(RULES_MAKE)
